services:
  app:
    container_name: web-audit
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always
    ports:
      - 3000:3000
    networks:
      - audit_network

  redis:
    container_name: web-audit-redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - audit_network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 54321:5432
    volumes:
      - audit_data:/var/lib/postgresql/data
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    networks:
      - audit_network

  electric:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/electric?sslmode=disable
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    networks:
      - audit_network

volumes:
  audit_data:

networks:
  audit_network:
