services:
  app:
    container_name: web-audit
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - 3000:3000
    networks:
      - audit_network
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - audit_data:/var/lib/postgresql/data
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    networks:
      - audit_network

  # zaproxy:
  #   image: zaproxy/zap-stable
  #   container_name: zaproxy
  #   command: zap-x.sh -daemon -host 0.0.0.0 -port 8080 -config database.recoverylog=false -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - audit_network

volumes:
  audit_data:

networks:
  audit_network:
