import type { Metadata } from "next";

import { ApiProvider } from "~/features/report";
import { ThemeRegistry } from "~/features/ui/components/ThemeRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <ApiProvider>{children}</ApiProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
