import type { Metadata } from "next";

import { RootLayout } from "~/features/ui/components/RootLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default RootLayout;
