import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export { RootLayout as default } from "~/features/common/components/RootLayout"
